# Generated by Django 4.0.5 on 2023-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lib_id',
            field=models.CharField(default='ABC123', max_length=50),
        ),
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
