# Generated by Django 4.0.5 on 2023-05-28 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artax', '0003_alter_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_registration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 15, 53, 38, 62541)),
        ),
    ]
