# Generated by Django 4.0.5 on 2023-05-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artax', '0004_alter_book_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_registration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 15, 55, 20, 876251)),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
