# Generated by Django 4.0.5 on 2023-06-04 08:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('artax', '0008_alter_client_landline_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='LB'),
        ),
    ]
