# Generated by Django 4.2.4 on 2023-08-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artax", "0010_remove_book_location_book_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="locations",
        ),
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book",
                to="artax.location",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book",
                to="artax.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book",
                to="artax.type",
            ),
        ),
    ]
